repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
    - id: check-added-large-files
      args: ["--maxkb=500"]
    - id: check-json
    - id: check-symlinks
    - id: check-xml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: ["--markdown-linebreak-ext=md"]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort
      args: ["--profile", "black"]

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    - id: black
      description: Format python code

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args: ["--max-line-length=88", "--extend-ignore=E203,E501,W503", "--per-file-ignores=__init__.py:F401"]
      additional_dependencies:
        - flake8-black>=0.1.1
      language_version: python3
      description: Linting for python code
